platform :ios, '10.0'
use_frameworks!

# use local version to simplify qa & release process
pod 'SparkLib', :path => '../../'

def add_spark
  pod 'SparkPlayer', :path => '../../'
end

target 'spark-demo' do
  add_spark
end

target 'preview-notification-content' do
  add_spark
end

target 'preview-notification-service' do
  add_spark
end
